/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlidesSlideIdRouteImport } from './routes/slides.$slideId'
import { Route as SlidesSlideIdStepRouteImport } from './routes/slides.$slideId.$step'

const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesSlideIdRoute = SlidesSlideIdRouteImport.update({
  id: '/$slideId',
  path: '/$slideId',
  getParentRoute: () => SlidesRoute,
} as any)
const SlidesSlideIdStepRoute = SlidesSlideIdStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => SlidesSlideIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/slides': typeof SlidesRouteWithChildren
  '/slides/$slideId': typeof SlidesSlideIdRouteWithChildren
  '/slides/$slideId/$step': typeof SlidesSlideIdStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/slides': typeof SlidesRouteWithChildren
  '/slides/$slideId': typeof SlidesSlideIdRouteWithChildren
  '/slides/$slideId/$step': typeof SlidesSlideIdStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/slides': typeof SlidesRouteWithChildren
  '/slides/$slideId': typeof SlidesSlideIdRouteWithChildren
  '/slides/$slideId/$step': typeof SlidesSlideIdStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/slides' | '/slides/$slideId' | '/slides/$slideId/$step'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/slides' | '/slides/$slideId' | '/slides/$slideId/$step'
  id:
    | '__root__'
    | '/'
    | '/slides'
    | '/slides/$slideId'
    | '/slides/$slideId/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlidesRoute: typeof SlidesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/$slideId': {
      id: '/slides/$slideId'
      path: '/$slideId'
      fullPath: '/slides/$slideId'
      preLoaderRoute: typeof SlidesSlideIdRouteImport
      parentRoute: typeof SlidesRoute
    }
    '/slides/$slideId/$step': {
      id: '/slides/$slideId/$step'
      path: '/$step'
      fullPath: '/slides/$slideId/$step'
      preLoaderRoute: typeof SlidesSlideIdStepRouteImport
      parentRoute: typeof SlidesSlideIdRoute
    }
  }
}

interface SlidesSlideIdRouteChildren {
  SlidesSlideIdStepRoute: typeof SlidesSlideIdStepRoute
}

const SlidesSlideIdRouteChildren: SlidesSlideIdRouteChildren = {
  SlidesSlideIdStepRoute: SlidesSlideIdStepRoute,
}

const SlidesSlideIdRouteWithChildren = SlidesSlideIdRoute._addFileChildren(
  SlidesSlideIdRouteChildren,
)

interface SlidesRouteChildren {
  SlidesSlideIdRoute: typeof SlidesSlideIdRouteWithChildren
}

const SlidesRouteChildren: SlidesRouteChildren = {
  SlidesSlideIdRoute: SlidesSlideIdRouteWithChildren,
}

const SlidesRouteWithChildren =
  SlidesRoute._addFileChildren(SlidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlidesRoute: SlidesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
