/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlidesIndexRouteImport } from './routes/slides.index'
import { Route as SlidesSpecRouteImport } from './routes/slides.spec'
import { Route as SlidesSlideIdRouteImport } from './routes/slides.$slideId'
import { Route as AudienceSessionIdRouteImport } from './routes/audience.$sessionId'
import { Route as SlidesSlideIdIndexRouteImport } from './routes/slides.$slideId.index'
import { Route as SlidesSlideIdStepRouteImport } from './routes/slides.$slideId.$step'

const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesIndexRoute = SlidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlidesRoute,
} as any)
const SlidesSpecRoute = SlidesSpecRouteImport.update({
  id: '/spec',
  path: '/spec',
  getParentRoute: () => SlidesRoute,
} as any)
const SlidesSlideIdRoute = SlidesSlideIdRouteImport.update({
  id: '/$slideId',
  path: '/$slideId',
  getParentRoute: () => SlidesRoute,
} as any)
const AudienceSessionIdRoute = AudienceSessionIdRouteImport.update({
  id: '/audience/$sessionId',
  path: '/audience/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesSlideIdIndexRoute = SlidesSlideIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlidesSlideIdRoute,
} as any)
const SlidesSlideIdStepRoute = SlidesSlideIdStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => SlidesSlideIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/slides': typeof SlidesRouteWithChildren
  '/audience/$sessionId': typeof AudienceSessionIdRoute
  '/slides/$slideId': typeof SlidesSlideIdRouteWithChildren
  '/slides/spec': typeof SlidesSpecRoute
  '/slides/': typeof SlidesIndexRoute
  '/slides/$slideId/$step': typeof SlidesSlideIdStepRoute
  '/slides/$slideId/': typeof SlidesSlideIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audience/$sessionId': typeof AudienceSessionIdRoute
  '/slides/spec': typeof SlidesSpecRoute
  '/slides': typeof SlidesIndexRoute
  '/slides/$slideId/$step': typeof SlidesSlideIdStepRoute
  '/slides/$slideId': typeof SlidesSlideIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/slides': typeof SlidesRouteWithChildren
  '/audience/$sessionId': typeof AudienceSessionIdRoute
  '/slides/$slideId': typeof SlidesSlideIdRouteWithChildren
  '/slides/spec': typeof SlidesSpecRoute
  '/slides/': typeof SlidesIndexRoute
  '/slides/$slideId/$step': typeof SlidesSlideIdStepRoute
  '/slides/$slideId/': typeof SlidesSlideIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/slides'
    | '/audience/$sessionId'
    | '/slides/$slideId'
    | '/slides/spec'
    | '/slides/'
    | '/slides/$slideId/$step'
    | '/slides/$slideId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audience/$sessionId'
    | '/slides/spec'
    | '/slides'
    | '/slides/$slideId/$step'
    | '/slides/$slideId'
  id:
    | '__root__'
    | '/'
    | '/slides'
    | '/audience/$sessionId'
    | '/slides/$slideId'
    | '/slides/spec'
    | '/slides/'
    | '/slides/$slideId/$step'
    | '/slides/$slideId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlidesRoute: typeof SlidesRouteWithChildren
  AudienceSessionIdRoute: typeof AudienceSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/': {
      id: '/slides/'
      path: '/'
      fullPath: '/slides/'
      preLoaderRoute: typeof SlidesIndexRouteImport
      parentRoute: typeof SlidesRoute
    }
    '/slides/spec': {
      id: '/slides/spec'
      path: '/spec'
      fullPath: '/slides/spec'
      preLoaderRoute: typeof SlidesSpecRouteImport
      parentRoute: typeof SlidesRoute
    }
    '/slides/$slideId': {
      id: '/slides/$slideId'
      path: '/$slideId'
      fullPath: '/slides/$slideId'
      preLoaderRoute: typeof SlidesSlideIdRouteImport
      parentRoute: typeof SlidesRoute
    }
    '/audience/$sessionId': {
      id: '/audience/$sessionId'
      path: '/audience/$sessionId'
      fullPath: '/audience/$sessionId'
      preLoaderRoute: typeof AudienceSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/$slideId/': {
      id: '/slides/$slideId/'
      path: '/'
      fullPath: '/slides/$slideId/'
      preLoaderRoute: typeof SlidesSlideIdIndexRouteImport
      parentRoute: typeof SlidesSlideIdRoute
    }
    '/slides/$slideId/$step': {
      id: '/slides/$slideId/$step'
      path: '/$step'
      fullPath: '/slides/$slideId/$step'
      preLoaderRoute: typeof SlidesSlideIdStepRouteImport
      parentRoute: typeof SlidesSlideIdRoute
    }
  }
}

interface SlidesSlideIdRouteChildren {
  SlidesSlideIdStepRoute: typeof SlidesSlideIdStepRoute
  SlidesSlideIdIndexRoute: typeof SlidesSlideIdIndexRoute
}

const SlidesSlideIdRouteChildren: SlidesSlideIdRouteChildren = {
  SlidesSlideIdStepRoute: SlidesSlideIdStepRoute,
  SlidesSlideIdIndexRoute: SlidesSlideIdIndexRoute,
}

const SlidesSlideIdRouteWithChildren = SlidesSlideIdRoute._addFileChildren(
  SlidesSlideIdRouteChildren,
)

interface SlidesRouteChildren {
  SlidesSlideIdRoute: typeof SlidesSlideIdRouteWithChildren
  SlidesSpecRoute: typeof SlidesSpecRoute
  SlidesIndexRoute: typeof SlidesIndexRoute
}

const SlidesRouteChildren: SlidesRouteChildren = {
  SlidesSlideIdRoute: SlidesSlideIdRouteWithChildren,
  SlidesSpecRoute: SlidesSpecRoute,
  SlidesIndexRoute: SlidesIndexRoute,
}

const SlidesRouteWithChildren =
  SlidesRoute._addFileChildren(SlidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlidesRoute: SlidesRouteWithChildren,
  AudienceSessionIdRoute: AudienceSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
