/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlidesIndexRouteImport } from './routes/slides.index'
import { Route as SlidesSlideIdIndexRouteImport } from './routes/slides.$slideId.index'
import { Route as SlidesSlideIdStepRouteImport } from './routes/slides.$slideId.$step'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesIndexRoute = SlidesIndexRouteImport.update({
  id: '/slides/',
  path: '/slides/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesSlideIdIndexRoute = SlidesSlideIdIndexRouteImport.update({
  id: '/slides/$slideId/',
  path: '/slides/$slideId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesSlideIdStepRoute = SlidesSlideIdStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => SlidesSlideIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/slides/': typeof SlidesIndexRoute
  '/slides/$slideId/$step': typeof SlidesSlideIdStepRoute
  '/slides/$slideId/': typeof SlidesSlideIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/slides': typeof SlidesIndexRoute
  '/slides/$slideId/$step': typeof SlidesSlideIdStepRoute
  '/slides/$slideId': typeof SlidesSlideIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/slides/': typeof SlidesIndexRoute
  '/slides/$slideId/$step': typeof SlidesSlideIdStepRoute
  '/slides/$slideId/': typeof SlidesSlideIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/slides/' | '/slides/$slideId/$step' | '/slides/$slideId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/slides' | '/slides/$slideId/$step' | '/slides/$slideId'
  id:
    | '__root__'
    | '/'
    | '/slides/'
    | '/slides/$slideId/$step'
    | '/slides/$slideId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlidesIndexRoute: typeof SlidesIndexRoute
  SlidesSlideIdIndexRoute: typeof SlidesSlideIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/': {
      id: '/slides/'
      path: '/slides'
      fullPath: '/slides/'
      preLoaderRoute: typeof SlidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/$slideId/': {
      id: '/slides/$slideId/'
      path: '/slides/$slideId'
      fullPath: '/slides/$slideId/'
      preLoaderRoute: typeof SlidesSlideIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/$slideId/$step': {
      id: '/slides/$slideId/$step'
      path: '/$step'
      fullPath: '/slides/$slideId/$step'
      preLoaderRoute: typeof SlidesSlideIdStepRouteImport
      parentRoute: typeof SlidesSlideIdRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlidesIndexRoute: SlidesIndexRoute,
  SlidesSlideIdIndexRoute: SlidesSlideIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
